### PR TITLE
adding Fastlane data for DE; better formatting for EN fulldesc

### PR DESCRIPTION
**Pull request by IzzySoft**
Feel free to include them with your PR "further upstream" :wink:

### CODE REVIEW

**Comment by SynapseScribe** [comment]
Please unlock issues section. How do i report bugs?

**Comment by MuntashirAkon** [comment]
> Please unlock issues section. How do i report bugs?

Open issue in the main repo.

**Comment by SynapseScribe** [comment]
which is main repo? thanks. 


update: i suppose https://github.com/miracle2k/android-autostarts
but that looks unmaintained anymore..

**Comment by MuntashirAkon** [comment]
> but that looks unmaintained anymore..

Yeah, I've just made a pull request there. The dev has agreed that he'll at least do some maintenance. Besides I will not be maintaining it as well (the app is old and uses many deprecated features). I initially forked it so that I can make a build for myself to test how it works so that I can add similar features to App Manager. But after visiting the issues on the repo and reviews on Google Play, I've decided to provide a build for the community as well so that others can benefit from the app.

**Comment by SynapseScribe** [comment]
I use App Manager as well, great work. So is autostarts going to be implemented inside it? Personally i tried autostarts on Android 10 but seem to be missbehaving. For example when i disable an app, several others are being disabled as well at the same time.

**Comment by MuntashirAkon** [comment]
> Personally i tried autostarts on Android 10 but seem to be missbehaving. For example when i disable an app, several others are being disabled as well at the same time.

Happened to me as well. But I'll not be using the exact implementation though. I will be using Intent Firewall, not `pm` command as it's unreliable.

**Comment by SynapseScribe** [comment]
Thank you for clarifying the situation and keep up the excelent work. I was browsing your projects and realised I use a lot of apps you developed.

**Comment by IzzySoft** [comment]
And thanks for merging! I just enabled "pulling" of `full_description.txt` as well now, so updates to it will be reflected with new releases.

**Pull request merged**
